package no.nav.familie.inntektsmelding.koder;

public enum ForespørselType {
    BESTILT_AV_FAGSYSTEM,
    BESTILT_AV_SAKSBEHANDLER,
    ARBEIDSGIVERINITIERT_NYANSATT,
    ARBEIDSGIVERINITIERT_UREGISTRERT,
    OMSORGSPENGER_REFUSJON
}
