kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: k9-inntektsmelding
  namespace: k9saksbehandling
  labels:
    team: k9saksbehandling
spec:
  image: {{image}}
  port: 8080
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  liveness:
    path: /k9/inntektsmelding/internal/health/isAlive
    initialDelay: 10
    periodSeconds: 10
    failureThreshold: 20
    timeout: 3
  readiness:
    path: /k9/inntektsmelding/internal/health/isReady
    initialDelay: 10
    periodSeconds: 10
    failureThreshold: 20
    timeout: 3
  preStopHook:
    http:
      path: /k9/inntektsmelding/internal/health/preStop
  prometheus:
    enabled: true
    path: /k9/inntektsmelding/internal/metrics/prometheus
  observability:
    logging:
      destinations:
        - id: "loki"
        - id: "elastic"
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
    scalingStrategy:
      cpu:
        thresholdPercentage: 80
  resources:
    limits:
      cpu: "{{limits.cpu}}"
      memory: "{{limits.mem}}"
    requests:
      cpu: "{{requests.cpu}}"
      memory: "{{requests.mem}}"
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        databases:
          - name: k9-inntektsmelding
            envVarPrefix: DB
        tier: {{dbTier}}
        diskAutoresize: {{dbDiskAutoresize}}
        highAvailability: {{dbHighAvailability}}
        pointInTimeRecovery: {{dbPointInTimeRecovery}}
        collation: nb_NO.UTF8
        {{#if enableDBAudit}}
        flags:
          - name: "cloudsql.enable_pgaudit"
            value: "on"
          - name: "pgaudit.log"
            value: "write"
          - name: "pgaudit.log_parameter"
            value: "on"
        {{/if}}
  secureLogs:
    enabled: true
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        extra:
          - "NAVident"
          - "azp_name"
        groups:
          - id: {{driftGruppeOid}}
  accessPolicy:
    inbound:
      rules:
        - application: k9-swagger
          namespace: k9saksbehandling
          permissions:
            scopes:
              - swagger
        - application: k9-sak
          namespace: k9saksbehandling
          cluster: {{environment}}-fss
        - application: k9-inntektsmelding-frontend
    outbound:
      rules:
        - application: notifikasjon-produsent-api
          namespace: fager
        - application: altinn-rettigheter-proxy
          namespace: arbeidsgiver
        - application: k9-dokgen
          namespace: k9saksbehandling
          cluster: {{environment}}-gcp
      external:
        - host: pdl-api.{{environment}}-fss-pub.nais.io
        - host: team-inntekt-proxy.{{environment}}-fss-pub.nais.io
        - host: ereg-services.{{environment}}-fss-pub.nais.io
        - host: k9sak-api.{{environment}}-fss-pub.nais.io
        - host: aareg-services.{{environment}}-fss-pub.nais.io
      {{#if devOnly}}
        - host: dokarkiv-q2.{{environment}}-fss-pub.nais.io
      {{else}}
        - host: dokarkiv.{{environment}}-fss-pub.nais.io
      {{/if}}
  env:
    - name: gruppe.oid.drift
      value: {{driftGruppeOid}}
