CREATE TABLE SAK
(
    ID   BIGINT PRIMARY KEY,
    GRUPPERING_UUID UUID,
    FAGER_SAK_ID VARCHAR(36),
    SAK_STATUS VARCHAR(100) default 'UNDER_BEHANDLING' NOT NULL,
    ORGNR VARCHAR(12) NOT NULL,
    BRUKER_AKTOER_ID VARCHAR(13) NOT NULL,
    YTELSE_TYPE VARCHAR(100) NOT NULL,
    FAGSYSTEM_SAKSNUMMER VARCHAR(19) NOT NULL,
    OPPRETTET_TID TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ENDRET_TID TIMESTAMP(3)
);

create sequence if not exists SEQ_SAK increment by 50 minvalue 1000000;

create unique index IDX_SAK_PRIMARY_KEY on SAK (ID);
create unique index IDX_SAK_FAGER_ID on SAK (FAGER_SAK_ID);
create index IDX_SAK_ORGNR_BRUKER_YTELSE_SAKSNR on SAK (ORGNR, BRUKER_AKTOER_ID, YTELSE_TYPE);

comment on table SAK is 'En forespørsel til arbeidsgiver';
comment on column SAK.ID is 'PK';
comment on column SAK.GRUPPERING_UUID is 'Grupperingsid for sak og oppgaver hos arbeidsgivernotifikasjon';
comment on column SAK.FAGER_SAK_ID is 'Ekstern sak-id hos fager/arbeidsgivernotifikasjon';
comment on column SAK.SAK_STATUS is 'Status på sak';
comment on column SAK.ORGNR is 'Orgnr for arbeidsgiver';
comment on column SAK.BRUKER_AKTOER_ID is 'Aktørid for bruker';
comment on column SAK.YTELSE_TYPE is 'Ytelsetype som forespørsel gjelder for';
comment on column SAK.FAGSYSTEM_SAKSNUMMER is 'Saksnummer fra fagsystem';


INSERT INTO SAK (ID, FAGER_SAK_ID, SAK_STATUS, ORGNR, BRUKER_AKTOER_ID, YTELSE_TYPE, FAGSYSTEM_SAKSNUMMER)
select nextval('SEQ_SAK'), SAK_ID, SAK_STATUS, ORGNR, BRUKER_AKTOER_ID, YTELSE_TYPE, FAGSYSTEM_SAKSNUMMER from FORESPOERSEL;


ALTER TABLE FORESPOERSEL ADD COLUMN INTERN_SAK_ID BIGINT REFERENCES SAK;
ALTER TABLE FORESPOERSEL ADD COLUMN FORESPOERSEL_STATUS VARCHAR(100) default 'NY' NOT NULL;

UPDATE FORESPOERSEL SET INTERN_SAK_ID = S.ID, FORESPOERSEL_STATUS = 'UTFOERT'
    from SAK s
    where SAK_ID = s.FAGER_SAK_ID and s.SAK_STATUS != 'UNDER_BEHANDLING';

UPDATE FORESPOERSEL SET INTERN_SAK_ID = S.ID, FORESPOERSEL_STATUS = 'NY'
    from SAK s
where SAK_ID = s.FAGER_SAK_ID and s.SAK_STATUS = 'UNDER_BEHANDLING';


ALTER TABLE FORESPOERSEL
ALTER COLUMN INTERN_SAK_ID SET NOT NULL;

ALTER TABLE FORESPOERSEL DROP COLUMN SAK_ID;
ALTER TABLE FORESPOERSEL DROP COLUMN ORGNR;
ALTER TABLE FORESPOERSEL DROP COLUMN BRUKER_AKTOER_ID;
ALTER TABLE FORESPOERSEL DROP COLUMN YTELSE_TYPE;
ALTER TABLE FORESPOERSEL DROP COLUMN FAGSYSTEM_SAKSNUMMER;


