-- Create the OMSORGSPENGER table
CREATE TABLE OMSORGSPENGER (
    ID BIGINT PRIMARY KEY,
    INNTEKTSMELDING_ID BIGINT NOT NULL,
    HAR_UTBETALT_PLIKTIGE_DAGER BOOLEAN NOT NULL,
    CONSTRAINT FK_OMSORGSPENGER_INNTEKTSMELDING FOREIGN KEY (INNTEKTSMELDING_ID) REFERENCES INNTEKTSMELDING(ID)
);

-- Create the FRAVAERS_PERIODE table
CREATE TABLE FRAVAERS_PERIODE (
    ID BIGINT PRIMARY KEY,
    OMSORGSPENGER_ID BIGINT NOT NULL,
    FOM DATE NOT NULL,
    TOM DATE NOT NULL,
    CONSTRAINT FK_FRAVAERS_PERIODE_OMSORGSPENGER FOREIGN KEY (OMSORGSPENGER_ID) REFERENCES OMSORGSPENGER(ID)
);

-- Create the DELVIS_FRAVAERS_PERIODE table
CREATE TABLE DELVIS_FRAVAERS_PERIODE (
    ID BIGINT PRIMARY KEY,
    OMSORGSPENGER_ID BIGINT NOT NULL,
    DATO DATE NOT NULL,
    TIMER NUMERIC(5, 2) NOT NULL,
    CONSTRAINT FK_DELVIS_FRAVAERS_PERIODE_OMSORGSPENGER FOREIGN KEY (OMSORGSPENGER_ID) REFERENCES OMSORGSPENGER(ID)
);

-- Create unique indexes for the primary keys
CREATE UNIQUE INDEX IDX_OMSORGSPENGER_PRIMARY_KEY ON OMSORGSPENGER (ID);
CREATE UNIQUE INDEX IDX_FRAVAERS_PERIODE_PRIMARY_KEY ON FRAVAERS_PERIODE (ID);
CREATE UNIQUE INDEX IDX_DELVIS_FRAVAERS_PERIODE_PRIMARY_KEY ON DELVIS_FRAVAERS_PERIODE (ID);

-- Add comments to the tables and columns
COMMENT ON TABLE OMSORGSPENGER IS 'Tabell for Omsorgspenger';
COMMENT ON COLUMN OMSORGSPENGER.ID IS 'Primary key';
COMMENT ON COLUMN OMSORGSPENGER.INNTEKTSMELDING_ID IS 'Foreign key til INNTEKTSMELDING tabell';
COMMENT ON COLUMN OMSORGSPENGER.HAR_UTBETALT_PLIKTIGE_DAGER IS 'Indikerer om arbeidsgiver har utbetalt pliktige dager';

COMMENT ON TABLE FRAVAERS_PERIODE IS 'Tabell for FraværsPeriode';
COMMENT ON COLUMN FRAVAERS_PERIODE.ID IS 'Primary key';
COMMENT ON COLUMN FRAVAERS_PERIODE.OMSORGSPENGER_ID IS 'Foreign key til OMSORGSPENGER tabell';
COMMENT ON COLUMN FRAVAERS_PERIODE.FOM IS 'Startdato for fraværsperioden';
COMMENT ON COLUMN FRAVAERS_PERIODE.TOM IS 'Sluttdato for fraværsperioden';

COMMENT ON TABLE DELVIS_FRAVAERS_PERIODE IS 'Tabell for DelvisFraværsPeriode';
COMMENT ON COLUMN DELVIS_FRAVAERS_PERIODE.ID IS 'Primary key';
COMMENT ON COLUMN DELVIS_FRAVAERS_PERIODE.OMSORGSPENGER_ID IS 'Foreign key til OMSORGSPENGER tabell';
COMMENT ON COLUMN DELVIS_FRAVAERS_PERIODE.DATO IS 'Dato for delvisfraværsperiode';
COMMENT ON COLUMN DELVIS_FRAVAERS_PERIODE.TIMER IS 'Antall fraværstimer for delvisfraværsperiode';
