-- Legg til LOEPENR-kolonne på FORESPOERSEL og INNTEKTSMELDING

CREATE SEQUENCE SEQ_FORESPOERSEL_LOEPENR START WITH 1 INCREMENT BY 1 NO CYCLE;
CREATE SEQUENCE SEQ_INNTEKTSMELDING_LOEPENR START WITH 1 INCREMENT BY 1 NO CYCLE;

ALTER TABLE FORESPOERSEL ADD COLUMN LOEPENR BIGINT;
ALTER TABLE INNTEKTSMELDING ADD COLUMN LOEPENR BIGINT;

-- Populer eksisterende rader sekvensielt etter opprettet tidspunkt
UPDATE FORESPOERSEL SET LOEPENR = sub.rn
FROM (SELECT ID, ROW_NUMBER() OVER (ORDER BY OPPRETTET_TID) AS rn FROM FORESPOERSEL) sub
WHERE FORESPOERSEL.ID = sub.ID;

UPDATE INNTEKTSMELDING SET LOEPENR = sub.rn
FROM (SELECT ID, ROW_NUMBER() OVER (ORDER BY OPPRETTET_TID) AS rn FROM INNTEKTSMELDING) sub
WHERE INNTEKTSMELDING.ID = sub.ID;

-- Sett NOT NULL og UNIQUE etter populering
ALTER TABLE FORESPOERSEL ALTER COLUMN LOEPENR SET NOT NULL;
ALTER TABLE FORESPOERSEL ADD CONSTRAINT UIDX_FORESPOERSEL_LOEPENR UNIQUE (LOEPENR);

ALTER TABLE INNTEKTSMELDING ALTER COLUMN LOEPENR SET NOT NULL;
ALTER TABLE INNTEKTSMELDING ADD CONSTRAINT UIDX_INNTEKTSMELDING_LOEPENR UNIQUE (LOEPENR);

-- Opprett sekvenser og sett neste verdi basert på eksisterende data
SELECT setval('SEQ_FORESPOERSEL_LOEPENR', COALESCE((SELECT MAX(LOEPENR) FROM FORESPOERSEL), 0) + 1, false);
SELECT setval('SEQ_INNTEKTSMELDING_LOEPENR', COALESCE((SELECT MAX(LOEPENR) FROM INNTEKTSMELDING), 0) + 1, false);

-- Sett default til sekvens for nye rader
ALTER TABLE FORESPOERSEL ALTER COLUMN LOEPENR SET DEFAULT nextval('SEQ_FORESPOERSEL_LOEPENR');
ALTER TABLE INNTEKTSMELDING ALTER COLUMN LOEPENR SET DEFAULT nextval('SEQ_INNTEKTSMELDING_LOEPENR');

COMMENT ON COLUMN FORESPOERSEL.LOEPENR IS 'Sekvensiell identifikator for forespørselen, eksponert til konsumenter';
COMMENT ON COLUMN INNTEKTSMELDING.LOEPENR IS 'Sekvensiell identifikator for inntektsmeldingen, eksponert til konsumenter';
