-- Create the ETTERSPURT_PERIODE table
CREATE TABLE ETTERSPURT_PERIODE (
    ID BIGINT PRIMARY KEY,
    FORESPOERSEL_ID BIGINT NOT NULL,
    FOM DATE NOT NULL,
    TOM DATE NOT NULL,
    CONSTRAINT FK_ETTERSPURT_PERIODE_FORESPOERSEL FOREIGN KEY (FORESPOERSEL_ID) REFERENCES FORESPOERSEL(ID)
);

-- Rename the primary key constraints
ALTER TABLE ETTERSPURT_PERIODE RENAME CONSTRAINT etterspurt_periode_pkey TO pk_etterspurt_periode;

-- Create indexes
CREATE INDEX idx_etterspurt_periode_id ON ETTERSPURT_PERIODE(FORESPOERSEL_ID);

-- Add comments to the tables and columns
COMMENT ON TABLE ETTERSPURT_PERIODE IS 'Tabell for Etterspurt Periode';
COMMENT ON COLUMN ETTERSPURT_PERIODE.ID IS 'Primary key';
COMMENT ON COLUMN ETTERSPURT_PERIODE.FORESPOERSEL_ID IS 'Foreign key til FORESPOERSEL tabell';
COMMENT ON COLUMN ETTERSPURT_PERIODE.FOM IS 'Startdato for perioden';
COMMENT ON COLUMN ETTERSPURT_PERIODE.TOM IS 'Sluttdato for perioden';
