-- Create the OMSORGSPENGER_FORESPOERSEL table
CREATE TABLE OMSORGSPENGER_FORESPOERSEL (
    ID BIGINT PRIMARY KEY,
    FORESPOERSEL_ID BIGINT NOT NULL,
    BEGRUNNELSE_FOR_SOEKNAD VARCHAR(300) NOT NULL,
    CONSTRAINT FK_OMSORGSPENGER_FORESPOERSEL FOREIGN KEY (FORESPOERSEL_ID) REFERENCES FORESPOERSEL(ID)
);

-- Create the FRAVAERS_PERIODE_FORESPOERSEL table
CREATE TABLE FRAVAERS_PERIODE_FORESPOERSEL (
    ID BIGINT PRIMARY KEY,
    OMSORGSPENGER_FORESPOERSEL_ID BIGINT NOT NULL,
    FOM DATE NOT NULL,
    TOM DATE NOT NULL,
    CONSTRAINT FK_FRAVAERS_PERIODE_FORESPOERSEL_OMSORGSPENGER_FORESPOERSEL FOREIGN KEY (OMSORGSPENGER_FORESPOERSEL_ID) REFERENCES OMSORGSPENGER_FORESPOERSEL(ID)
);

-- Create the DELVIS_FRAVAERS_DAG_FORESPOERSEL table
CREATE TABLE DELVIS_FRAVAERS_DAG_FORESPOERSEL (
    ID BIGINT PRIMARY KEY,
    OMSORGSPENGER_FORESPOERSEL_ID BIGINT NOT NULL,
    DATO DATE NOT NULL,
    FRAVAERS_TIMER NUMERIC(5, 2) NOT NULL,
    NORMAL_ARBEIDSTID NUMERIC(5, 2) NOT NULL,
    CONSTRAINT FK_DELVIS_FRAVAERS_DAG_FORESPOERSEL_OMSORGSPENGER_FORESPOERSEL FOREIGN KEY (OMSORGSPENGER_FORESPOERSEL_ID) REFERENCES OMSORGSPENGER_FORESPOERSEL(ID)
);

-- Rename the primary key constraints
ALTER TABLE OMSORGSPENGER_FORESPOERSEL RENAME CONSTRAINT omsorgspenger_forespoersel_pkey TO pk_omsorgspenger_forespoersel;
ALTER TABLE FRAVAERS_PERIODE_FORESPOERSEL RENAME CONSTRAINT fravaers_periode_forespoersel_pkey TO pk_fravaers_periode_forespoersel;
ALTER TABLE DELVIS_FRAVAERS_DAG_FORESPOERSEL RENAME CONSTRAINT delvis_fravaers_dag_forespoersel_pkey TO pk_delvis_fravaers_dag_forespoersel;

-- Create indexes
CREATE INDEX idx_omsorgspenger_forespoersel_id ON OMSORGSPENGER_FORESPOERSEL(FORESPOERSEL_ID);
CREATE INDEX idx_fravaers_periode_forespoersel_omsorgspenger_forespoersel_id ON FRAVAERS_PERIODE_FORESPOERSEL(OMSORGSPENGER_FORESPOERSEL_ID);
CREATE INDEX idx_delvis_fravaers_dag_forespoersel_omsorgspenger_forespoersel_id ON DELVIS_FRAVAERS_DAG_FORESPOERSEL(OMSORGSPENGER_FORESPOERSEL_ID);

-- Add comments to the tables and columns
COMMENT ON TABLE OMSORGSPENGER_FORESPOERSEL IS 'Tabell for Omsorgspenger Forespørsel';
COMMENT ON COLUMN OMSORGSPENGER_FORESPOERSEL.ID IS 'Primary key';
COMMENT ON COLUMN OMSORGSPENGER_FORESPOERSEL.FORESPOERSEL_ID IS 'Foreign key til FORESPOERSEL tabell';
COMMENT ON COLUMN OMSORGSPENGER_FORESPOERSEL.BEGRUNNELSE_FOR_SOEKNAD IS 'Brukers begrunnelse for søknad om omsorgspenger';

COMMENT ON TABLE FRAVAERS_PERIODE_FORESPOERSEL IS 'Tabell for FraværsPeriode';
COMMENT ON COLUMN FRAVAERS_PERIODE_FORESPOERSEL.ID IS 'Primary key';
COMMENT ON COLUMN FRAVAERS_PERIODE_FORESPOERSEL.OMSORGSPENGER_FORESPOERSEL_ID IS 'Foreign key til FORESPOERSEL tabell';
COMMENT ON COLUMN FRAVAERS_PERIODE_FORESPOERSEL.FOM IS 'Startdato for fraværsperioden';
COMMENT ON COLUMN FRAVAERS_PERIODE_FORESPOERSEL.TOM IS 'Sluttdato for fraværsperioden';

COMMENT ON TABLE DELVIS_FRAVAERS_DAG_FORESPOERSEL IS 'Tabell for DelvisFraværsPeriode';
COMMENT ON COLUMN DELVIS_FRAVAERS_DAG_FORESPOERSEL.ID IS 'Primary key';
COMMENT ON COLUMN DELVIS_FRAVAERS_DAG_FORESPOERSEL.OMSORGSPENGER_FORESPOERSEL_ID IS 'Foreign key til FORESPOERSEL tabell';
COMMENT ON COLUMN DELVIS_FRAVAERS_DAG_FORESPOERSEL.DATO IS 'Dato for delvis fraværsdag';
COMMENT ON COLUMN DELVIS_FRAVAERS_DAG_FORESPOERSEL.FRAVAERS_TIMER IS 'Antall fraværstimer for delvis fraværsdag';
COMMENT ON COLUMN DELVIS_FRAVAERS_DAG_FORESPOERSEL.NORMAL_ARBEIDSTID IS 'Antall timer bruker normalt jobber';
