-- Rename the OMSORGSPENGER table to OMSORGSPENGER_INNTEKTSMELDING
ALTER TABLE OMSORGSPENGER RENAME TO OMSORGSPENGER_INNTEKTSMELDING;

-- Rename the FRAVAERS_PERIODE table to FRAVAERS_PERIODE_INNTEKTSMELDING
ALTER TABLE FRAVAERS_PERIODE RENAME TO FRAVAERS_PERIODE_INNTEKTSMELDING;

-- Rename the DELVIS_FRAVAERS_PERIODE table to DELVIS_FRAVAERS_DAG_INNTEKTSMELDING
ALTER TABLE DELVIS_FRAVAERS_PERIODE RENAME TO DELVIS_FRAVAERS_DAG_INNTEKTSMELDING;
