ALTER TABLE IF EXISTS INNTEKTSMELDING ADD COLUMN FORESPORSEL_ID BIGINT;

ALTER TABLE INNTEKTSMELDING ADD CONSTRAINT FK_INNTEKTSMELDING_FORESPORSEL foreign key (FORESPORSEL_ID) references FORESPOERSEL;

CREATE INDEX IDX_INNTEKTSMELDING_FORESPORSEL_ID ON INNTEKTSMELDING (FORESPORSEL_ID);

COMMENT ON COLUMN INNTEKTSMELDING.FORESPORSEL_ID IS 'Foreign key til FORESPOERSEL tabell';
