ALTER TABLE INNTEKTSMELDING ADD COLUMN UUID UUID;

COMMENT ON COLUMN INNTEKTSMELDING.UUID IS 'En unik uuid som identifiserer inntektsmeldingen';
create unique index UIDX_INNTEKTSMELDING_UUID on INNTEKTSMELDING (UUID);

UPDATE INNTEKTSMELDING SET UUID = gen_random_uuid() WHERE UUID IS NULL;
ALTER TABLE INNTEKTSMELDING ALTER COLUMN UUID SET NOT NULL;
