
COMMENT ON COLUMN FORESPOERSEL.FORSTE_UTTAKSDATO IS 'Dat med første frævarsdag.';
COMMENT ON COLUMN FORESPOERSEL.STATUS IS 'Status på forespørselen.';

ALTER TABLE FORESPOERSEL RENAME CONSTRAINT "forespoersel_pkey" TO "pk_foresporsel_id";
ALTER TABLE REFUSJON_ENDRING RENAME CONSTRAINT "refusjon_endring_pkey" TO "pk_refusjon_endring_id";
ALTER TABLE BORTFALT_NATURALYTELSE RENAME CONSTRAINT "bortfalt_naturalytelse_pkey" TO "pk_bortfalt_naturalytelse_id";
ALTER TABLE ENDRINGSAARSAK RENAME CONSTRAINT "endringsaarsak_pkey" TO "pk_endringsaarsak_id";
ALTER TABLE KONTAKTPERSON RENAME CONSTRAINT "kontaktperson_pkey" TO "pk_kontaktperson_id";
ALTER TABLE INNTEKTSMELDING RENAME CONSTRAINT "inntektsmelding_pkey" TO "pk_inntektsmelding_id";

DROP INDEX idx_bortfalt_naturalytelse_primary_key;
DROP INDEX idx_endringsaarsak_primary_key;
DROP INDEX idx_forespoersel_primary_key;
DROP INDEX idx_inntektsmelding_primary_key;
DROP INDEX idx_refusjon_endring_primary_key;
DROP INDEX idx_kontaktperson_primary_key;

CREATE INDEX IDX_KONTAKTPERSON_INNTEKTSMELDING_ID ON KONTAKTPERSON(INNTEKTSMELDING_ID);
CREATE INDEX IDX_BORTFALT_NATURALYTELSE_INNTEKTSMELDING_ID ON BORTFALT_NATURALYTELSE(INNTEKTSMELDING_ID);
CREATE INDEX IDX_ENDRINGSAARSAK_INNTEKTSMELDING_ID ON ENDRINGSAARSAK(INNTEKTSMELDING_ID);
CREATE INDEX IDX_REFUSJON_ENDRING_INNTEKTSMELDING_ID ON REFUSJON_ENDRING(INNTEKTSMELDING_ID);

ALTER INDEX idx_forespoersel_uuid RENAME TO uidx_forespoersel_uuid;

