create index IDX_FORESPOERSEL_SAKSNUMMER on FORESPOERSEL (SAKSNUMMER);
create index IDX_FORESPOERSEL_BRUKER_YTELSE_ORGNR on FORESPOERSEL (BRUKER_AKTOER_ID, YTELSE_TYPE, ORGNR);
create index IDX_FORESPOERSEL_SAKID on FORESPOERSEL (SAK_ID);
drop index IDX_FORESPOERSEL_STP_ORGNR_BRUKER_YTELSE_SAKSNR;
