ALTER TABLE INNTEKTSMELDING ADD COLUMN status VARCHAR(50) DEFAULT 'GODKJENT';
UPDATE INNTEKTSMELDING SET status = 'GODKJENT' WHERE status IS NULL;
ALTER TABLE INNTEKTSMELDING ALTER COLUMN status SET NOT NULL;

COMMENT ON COLUMN INNTEKTSMELDING.status IS 'Status for inntektsmelding: GODKJENT, VENTER_VURDERING, AVVIST, UTDATERT';
