ALTER TABLE FORESPOERSEL ADD COLUMN DIALOGPORTEN_UUID UUID;

COMMENT ON COLUMN FORESPOERSEL.DIALOGPORTEN_UUID IS 'DialogId for forespørselen til bruk i Altinn - Dialogporten';

ALTER TABLE FORESPOERSEL ADD CONSTRAINT UIDX_FORESPOERSEL_DIALOGPORTEN_UUID UNIQUE (DIALOGPORTEN_UUID);
