name: Bygg og deploy

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**.md'
      - '**.MD'
      - '.gitignore'
      - '.editorconfig'
      - '.java-version'
      - 'LICENSE'
      - 'CODEOWNERS'
      - 'lokalutvikling/**'
      - '.github/*.yml'

jobs:
  build-app:
    name: Build
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: navikt/sif-gha-workflows/.github/workflows/maven-build-app-db.yml@main
    with:
      java-version: 21
      build-image: ${{ github.actor != 'dependabot[bot]' }}
      push-image: ${{ github.ref_name == github.event.repository.default_branch}}
    secrets: inherit

#  deploy-dev-k9saksbehandling:
#    name: Deploy dev
#    permissions:
#      id-token: write
#    if: github.ref_name == 'master'
#    needs: [build-app]
#    uses: navikt/k9-inntektsmelding/.github/workflows/deploy.yml@master
#    with:
#      image: ${{ needs.build-app.outputs.build-version }}
#      cluster: dev-gcp
#      namespace: k9saksbehandling
#    secrets: inherit
